#!/usr/bin/ash

run_hook() {
    if [ -e /sys/devices/platform/bootsplash.0/enabled ]; then
        echo 0 > /sys/devices/platform/bootsplash.0/enabled
    fi

    DEVICE=$(echo $root | sed 's/..$//')
    echo "The current storage device is $DEVICE"

    start=$(fdisk -l ${DEVICE} | grep ${DEVICE}p2 | sed 's/*//' | awk '{print $2}')
    echo "Rootfs start sector is $start"

    ROOTFS_FILESYSTYPE=$(fsck -N $root)

    case ${ROOTFS_FILESYSTYPE} in
        *fsck.f2fs*) FSRESIZER="/usr/sbin/resize.f2fs";;
        *fsck.ext*) FSRESIZER="/usr/sbin/resize2fs -f";;
    esac

    fdisk ${DEVICE} <<EOF
p
d
2
n
2
$start

w
EOF

    partx -u ${DEVICE}
    $FSRESIZER ${DEVICE}p2
    sync

    if [ -e /sys/devices/platform/bootsplash.0/enabled ]; then
        echo 1 > /sys/devices/platform/bootsplash.0/enabled
    fi
    
#configuring snapper    
umount /.snapshots
rm -r /.snapshots
snapper --no-dbus -c root create-config /
btrfs subvolume delete /.snapshots
mkdir /.snapshots
mount -a
chmod 750 /.snapshots
#Changing The timeline auto-snap
sed -i 's|QGROUP=""|QGROUP="1/0"|' /etc/snapper/configs/root
sed -i 's|NUMBER_LIMIT="50"|NUMBER_LIMIT="10-15"|' /etc/snapper/configs/root
sed -i 's|NUMBER_LIMIT_IMPORTANT="50"|NUMBER_LIMIT_IMPORTANT="5-10"|' /etc/snapper/configs/root
sed -i 's|TIMELINE_LIMIT_HOURLY="10"|TIMELINE_LIMIT_HOURLY="0"|' /etc/snapper/configs/root
sed -i 's|TIMELINE_LIMIT_DAILY="10"|TIMELINE_LIMIT_DAILY="3"|' /etc/snapper/configs/root
sed -i 's|TIMELINE_LIMIT_WEEKLY="0"|TIMELINE_LIMIT_WEEKLY="2"|' /etc/snapper/configs/root
sed -i 's|TIMELINE_LIMIT_MONTHLY="10"|TIMELINE_LIMIT_MONTHLY="2"|' /etc/snapper/configs/root
sed -i 's|TIMELINE_LIMIT_YEARLY="10"|TIMELINE_LIMIT_YEARLY="0"|' /etc/snapper/configs/root
systemctl enable snapper-timeline.timer
systemctl enable snapper-cleanup.timer

}

# vim: set ft=sh ts=4 sw=4 et:
